query GetViewerLeafFields{
    viewer {
        anyPinnableItems
        avatarUrl
        bio
        bioHTML
        company
        companyHTML
        createdAt
        databaseId
        email
        estimatedNextSponsorsPayoutInCents
        hasSponsorsListing
        id
        isBountyHunter
        isCampusExpert
        isDeveloperProgramMember
        isEmployee
        isFollowingViewer
        isGitHubStar
        isHireable
        isSiteAdmin
        isSponsoringViewer
        location
        login
        monthlyEstimatedSponsorsIncomeInCents
        name
        pinnedItemsRemaining
        projectsResourcePath
        projectsUrl
        pronouns
        resourcePath
        totalSponsorshipAmountAsSponsorInCents
        twitterUsername
        updatedAt
        url
        userViewType
        viewerCanChangePinnedItems
        viewerCanFollow
        viewerCanSponsor
        viewerCopilotAgentCreatesChannel
        viewerCopilotAgentLogUpdatesChannel
        viewerCopilotAgentTaskUpdatesChannel
        viewerCopilotAgentUpdatesChannel
        viewerIsFollowing
        viewerIsSponsoring
        websiteUrl
    }
}
